services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_app
    networks:
      - app_network
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
      - ./backend/storage:/var/www/html/storage
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel_db
      DB_USERNAME: custom_user
      DB_PASSWORD: custom_password
    command: /bin/bash -c "composer install && php artisan key:generate && php artisan migrate && php artisan serve --host=0.0.0.0 --port=8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue_app
    networks:
      - app_network
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  mysql:
    image: mysql:8.0
    container_name: mysql
    networks:
      - app_network
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: custom_user
      MYSQL_PASSWORD: custom_password
    volumes:
      - ./mysql_data:/var/lib/mysql

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
